### ISSUE TITLE
"It appears you're logged out of reddit" messages on 503 responses

### ISSUE THREAD

**Issue by hobbldygoop** [BoringCode/RedditNotifier#27]
I sometimes get notifications that say "It appears you're logged out of reddit". After checking the traffic this seems to happen when reddit returns a HTTP 503 Service Unavailable response with body:
    `<h2>all of our servers are busy right now</h2><h3>please try again in a minute</h3>`

This can get kinda annoying when reddit has a bad day and this happens frequently.

**Comment by BoringCode** [comment]
I'm going to rethink how error messages are displayed.

**Comment by LifeWulf** [comment]
Hiya, just wanted to report it's still happening.

**Comment by BoringCode** [comment]
I no longer report logged out errors. It fails silently.
