### ISSUE TITLE
Multiple notifications for the same message

### ISSUE THREAD

**Issue by LifeWulf** [BoringCode/RedditNotifier#28]
Hiya,

Often within the last few days (although not completely consistent), I'll go to check a notification that Notifier well, notified me about, and after upvoting whatever kind fellow replied to me, I'll suddenly get another notification. Clicking the Notifier button, I'm brought to my now-empty messages. My only conclusion is that it's registering the same notification twice with a delay just long enough that I have time to check it before it gets it again.

**Comment by BoringCode** [comment]
This can be fixed by changing your notification delay in the settings.

**Comment by LifeWulf** [comment]
What would you recommend? I currently have it set to 30 seconds.

**Comment by BoringCode** [comment]
Try 60, if this still keeps happening then there may be something else wrong.

Now that you mention it, it could be that you got two types of notifications (mod mail and mail for example) and when you clicked you only viewed one, but not the other. Sometimes it can get confused about which URL on reddit to take you to.

**Comment by LifeWulf** [comment]
I'll try 60. I only manage one sub and it's pretty dead, I don't get mod mail lol.
