### ISSUE TITLE
Can no longer right click to check for new messages

### ISSUE THREAD

**Issue by Two-Tone** [BoringCode/RedditNotifier#29]
Title pretty much says it all.  Running version 1.5.4

**Comment by Two-Tone** [comment]
Went back a couple versions, the issue still persists.  Hmm, I wonder whats causing it.

**Comment by MrsAngelD** [comment]
I'm having this issue as well

**Comment by LifeWulf** [comment]
Yep, same here. The extension is all but broken at this point. At the very least it still plays a notification sound and acts as a quick link to my messages, but if I'm not at my computer when the sound plays I won't know if I got a message.

**Comment by BoringCode** [comment]
Hey guys, I'm aware of this problem and I will be working on a fix in the coming weeks.
