### ISSUE TITLE
Icon badge and animation broken by Firefox 37.0.1 update?

### ISSUE THREAD

**Issue by lotsosmiley** [BoringCode/RedditNotifier#30]
I just got the FF v. 37.0.1 update installed on the computer I'm using now.  I know I had 3 unread messages thanks to Notifier before the update installed that I had not yet gone to check.  I restarted FF after the update, and although the pop-up that says there are new messages and how many appeared at the bottom, the icon shows no messages.  It also doesn't not seem to show the check message animation whether on the scheduled check or a manual check with a right-click.  It does also take me to messages if I left-click.  I know at least that and the notification itself are working since I did get the pop-up notification of messages, but the icon seems to be broken as far as any indication that it is working.  

This machine is Windows 7, no other updates, installs or add-ons added prior to the 37.0.1 update.

I also have a Windows 8.1 machine that I know got the FF update yesterday, but I wasn't using reddit on it yesterday so didn't notice any issue.  Checking it now though with those same 3 messages still unread, the icon there is doing the same thing.  Pop-up works if I close and re-open FF to reset that notice, but the icon shows nothing still and not arrow animation on check.

**Comment by MrsAngelD** [comment]
I have a similar issue. I get a notification sound but the button doesn't show any indication of a message and I get no pop up.

**Comment by Javro07** [comment]
I have the same issue since updating by Firefox. Icon no longer animates or shows number of received messages in Firefox 37.0.1 on Windows 8.1 install.

**Comment by LifeWulf** [comment]
Firefox 37.0.2 on Windows 8.1, toolbar button no longer shows unread notifications, but sounds still play just fine and clicking on it still brings me to the proper page.
