### ISSUE TITLE
Doesn't notify anymore

### ISSUE THREAD

**Issue by coreyg142** [BoringCode/RedditNotifier#38]
I can get messages on reddit, but this addon does not notify me anymore. Nothing on my end has changed since this issue started as far as I know.

**Comment by BoringCode** [comment]
Does the addon display the number of unread messages? Or is it completely failing to notify you?

Try visiting [this page](https://www.reddit.com/message/unread.json) when you have unread messages. Do they show up here? 

When you visit the settings page in about:addons is "display notifications" checked?

**Comment by Seblirium** [comment]
Jumping in here too with the same issue. 

> Does the addon display the number of unread messages? Or is it completely failing to notify you?

The add-on icon is no longer visible in my toolbar at all; even if I click 'Customize' in FF. No notifications at all.

> Try visiting this page when you have unread messages. Do they show up here?

No. I receive a 403 Forbidden. Request forbidden by administrative rules. 

> When you visit the settings page in about:addons is "display notifications" checked?

Yes, notifications (and auto-updates) are checked.

**Comment by BoringCode** [comment]
What version of Firefox are you using? What OS? What version of the
addon? Have you tried reinstalling the addon? 

As to the 403 forbidden error, are you sure you're logged into reddit?
The addon only works if you're logged in and that error indicates to me
that you aren't.

---
Bradley Rosenfeld 

On 2016-12-08 7:47 am, Seblirium wrote:

> Jumping in here too with the same issue.
> 
>> Does the addon display the number of unread messages? Or is it completely failing to notify you?
> 
> The add-on icon is no longer visible in my toolbar at all; even if I click 'Customize' in FF. No notifications at all.
> 
>> Try visiting this page when you have unread messages. Do they show up here?
> 
> No. I receive a 403 Forbidden. Request forbidden by administrative rules.
> 
>> When you visit the settings page in about:addons is "display notifications" checked?
> 
> Yes, notifications (and auto-updates) are checked. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/BoringCode/RedditNotifier/issues/38#issuecomment-265732128
[2]

**Comment by Seblirium** [comment]
> What version of Firefox are you using? What OS? What version of the addon? 

FF - 50.0.2. OS - Windows 10 Home (Build 1607). Add-on 2.0.3

> Have you tried reinstalling the addon? 

Yes. Removed, restarted FF, installed again, restarted FF.

> As to the 403 forbidden error, are you sure you're logged into reddit? The addon only works if you're logged in and that error indicates to me that you aren't.

Yes, logged in and browsing/posting all morning in the same browser.

**Comment by BoringCode** [comment]
I have no idea why you are getting the 403 error. That is a standard part of reddit and it should be returning a JSON string. Heck just to make sure I created a brand new test account and I was able to access it just fine. The error might be what is causing the addon to fail to notify you. 

As to the disappearing addon button, that reminds me of an old Firefox bug when using the Addon SDK. I'll try to reproduce your setup and see if it still fails.

**Comment by Seblirium** [comment]
Ok, I have an update.

Firstly; I tried the json link again in a private browsing window; and it worked. I then disabled https everywhere, and Ghostery, and tried again in my normal window; and it worked (I'm wondering if disabling these cleared a cached file or something). To be 100% sure, I then manually cleared the cache, and CTRL+F5 refreshed the link and it loads fine.

As for the disappearing addon button; that issue still remains.

For your reference; other addons installed are:
Add to Search Bar, Boomerang for Gmail, FEBE, FoxyProxy Standard (although not configured), Ghostery, Good search link fix, HTTPS Everywhere, lastpass, OneTab, Pushbullet, RES, (RedditNotifier), Steam Database, Strict Pop-up Blocker, YouTube HD Plus.

**Comment by coreyg142** [comment]
Sorry for not updating earlier, I have been neglecting to check my email.

> Does the addon display the number of unread messages? Or is it completely failing to notify you?

It is completely failing.

> Try visiting this page when you have unread messages. Do they show up here?

They do show up there.

>When you visit the settings page in about:addons is "display notifications" checked? 

Yes it is.

**Comment by basetian** [comment]
Having the same issue. Currently one unread message

> Does the addon display the number of unread messages? Or is it completely failing to notify you?

Completely failing to display anything

> Try visiting this page when you have unread messages. Do they show up here?

`{"kind": "Listing", "data": {"modhash": "xxxx", "children": [], "after": null, "before": null}}`

When you visit the settings page in about:addons is "display notifications" checked?
> Is checked

Browser is FF 50.1.0.

**Comment by coreyg142** [comment]
Hey is there any fix for this yet? It still is failing to notify me.

**Comment by BoringCode** [comment]
Sorry that I've disappeared on this issue, I've had a lot going on in my life.

I'm planning doing an update for Firefox 57 (because Mozilla is breaking older addons), and I'll see if I can roll fixes for this issue into it.
