### ISSUE TITLE
Notifier doesn't work with subreddit with "_" in the name like "battlefield_one"

### ISSUE THREAD

**Issue by BSlGuru** [BoringCode/RedditNotifier#39]
Hi, I don't get notifications for subreddits with "_" in the name like "battlefield_one", There the notification doesn't work.

**Comment by BoringCode** [comment]
I think the regex is broken. I'll a roll a fix for this into the
upcoming "compatibility with Firefox 57" update.

---
Bradley Rosenfeld
https://bradleyrosenfeld.com 

On 2017-03-22 12:03 pm, BSlGuru wrote:

> Hi, I don't get notifications for subreddits with "_" in the name like "battlefield_one", There the notification doesn't work. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/BoringCode/RedditNotifier/issues/39
[2]
